version: '3'
services:
  ssd-det:
    # network_mode: "host"
    build: .
    command: python -u app.py
    ports:
      - "80:5000"
    volumes:
      - .:/ssd-det
      - ../uploads:/uploadsD
      - ./dalle-mini-1:/ssd-det/dalle-mini-1
    environment:
      - MONGO_DATABASE=viva-api-responses
      - MONGO_USERNAME=apiBackend
      - MONGO_PASSWORD=apiBackendPwd
    deploy:
        resources:
            limits:
                cpus: "0.50"
                memory: 2000M
            reservations:
                cpus: "0.25"
                memory: 500M
